### PR TITLE
Update PDF files for protect by editing

### PR DESCRIPTION
**Pull request by Shunichi-K**
Next files needs to protect:
 CXD5602PWBEXT1/BOM/en_BOM_list.pdf
 CXD5602PWBEXT1/BOM/ja_BOM_list.pdf
 CXD5602PWBMAIN1/BOM/en_BOM_list.pdf
 CXD5602PWBMAIN1/BOM/ja_BOM_list.pdf
 main_board_addon_board/en_design_guidelines.pdf
 main_board_addon_board/ja_design_guidelines.pdf

### CODE REVIEW

**Comment by Toshiyuki-Iijima** [comment]
All files are OK! Thanks.

**Comment by Shunichi-K** [comment]
@Toshiyuki-Iijima san
Could you approve this pull request?

**Comment by Toshiyuki-Iijima** [comment]
Yes, off course.

**Comment by Shunichi-K** [comment]
@Toshiyuki-Iijima san

Could you set review status to "Approve"?
I cannot merge this change right now.

**Comment by Toshiyuki-Iijima** [comment]
OK.

**Pull request merged**
